# Generated by Django 2.2.4 on 2019-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='用户名'),
        ),
    ]
